package demo.service.impl;

import com.fasterxml.jackson.databind.ObjectMapper;
import demo.model.SimulatorInitLocations;
import demo.service.PathService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.io.InputStream;

@Service
public class DefaultPathService implements PathService {

    @Autowired // the mapper is generated by jackson.
    private ObjectMapper objectMapper;

    @Override
    public SimulatorInitLocations loadSimulatorInitLocatios() {
        // make use of resourse
        InputStream input =  this.getClass().getResourceAsStream("init-location.json");

        try {
            return objectMapper.readValue(input, SimulatorInitLocations.class);
        } catch (IOException e) {
            throw new IllegalStateException(e);
            // e.printStackTrace();
        }
    }
}
